### ISSUE TITLE
OutOfMemory exception

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#49]
After a longer runtime of the CM, the CM backend data storage becomes too large, so that an OutOfMemory exception is thrown and the application is no longer operable.

```
06:43:05.330 [http-nio-8080-exec-7] INFO - UUID is : 49b3aed5-91fe-44e4-b1fd-f97b31e5c840
06:43:20.552 [http-nio-8080-exec-1] ERROR - Out of memory.; SQL statement:
update config_model_object set configuration_model=? where id=? [90108-200]
06:43:20.558 [http-nio-8080-exec-1] ERROR - Application exception overridden by rollback exception
javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: could not execute statement
                at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
                at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
                at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]

```

**Comment by tmberthold** [comment]
Main problem here is solved on bugfixes brach, will be released soon.

Still undergoing investigations if it can happen again in other cases.

**Comment by tmberthold** [comment]
Should not happen again, otherwise this will be reopened.
